version: "2"
linters:
  default: none
  enable:
    - bidichk
    - durationcheck
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
        path: http2utils/utils.go
      - path: (hpack|serverConn)\.go
        text: SA6002
      - path: (.+)\.go$
        text: 'ST1000: at least one file in a package should have a package comment'
    paths:
      - examples
      - benchmark
      - cmd
      - maybe_later
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - examples
      - benchmark
      - cmd
      - maybe_later
      - third_party$
      - builtin$
      - examples$
